const fs = require('fs');
const path = require('path');

const OUTPUT_DIR = path.resolve(__dirname, '../data/source_documents');

const AI_DOCUMENTS = [
  { id: 'ai_01', title: 'Introduction to Artificial Intelligence', content: 'Artificial Intelligence (AI) is the field of computer science focused on creating systems that perform tasks requiring human-like intelligence. Core goals include reasoning, learning, perception, and language understanding. Modern AI combines symbolic methods, statistical learning, and large-scale neural networks. Applications span healthcare, finance, robotics, and education. Responsible AI development requires attention to bias, transparency, safety, and human oversight.' },
  { id: 'ai_02', title: 'Machine Learning Fundamentals', content: 'Machine learning enables computers to improve performance on tasks through experience without explicit programming for every rule. Supervised learning uses labeled examples to predict outputs. Unsupervised learning discovers structure in unlabeled data. Reinforcement learning optimizes actions via rewards. Key concepts include features, labels, training sets, validation, overfitting, and generalization. Popular algorithms include linear regression, decision trees, random forests, and gradient boosting.' },
  { id: 'ai_03', title: 'Deep Learning and Neural Networks', content: 'Deep learning uses multi-layer neural networks to learn hierarchical representations from data. Layers of neurons apply weighted sums and nonlinear activations such as ReLU. Convolutional neural networks excel at images; recurrent and transformer architectures excel at sequences. Training uses backpropagation and optimizers like Adam. Challenges include vanishing gradients, data requirements, and compute cost. Transfer learning reuses pretrained models for new tasks.' },
  { id: 'ai_04', title: 'Natural Language Processing Overview', content: 'Natural Language Processing (NLP) enables machines to understand, interpret, and generate human language. Tasks include tokenization, part-of-speech tagging, named entity recognition, sentiment analysis, machine translation, and question answering. Modern NLP relies on transformers and self-attention. Word embeddings capture semantic similarity. Large language models are pretrained on vast corpora and fine-tuned for downstream applications.' },
  { id: 'ai_05', title: 'Computer Vision Basics', content: 'Computer vision extracts information from images and video. Tasks include classification, object detection, segmentation, and pose estimation. Pipelines involve acquisition, preprocessing, feature extraction, and inference. CNNs revolutionized vision benchmarks. Data augmentation improves robustness. Metrics include accuracy, precision, recall, and mean average precision. Ethical concerns include surveillance, deepfakes, and biased facial recognition systems.' },
  { id: 'ai_06', title: 'Reinforcement Learning Principles', content: 'Reinforcement learning trains agents to maximize cumulative reward in environments. Components include states, actions, policies, and value functions. Exploration versus exploitation is central. Algorithms include Q-learning, SARSA, policy gradients, and actor-critic methods. Deep reinforcement learning combines neural networks with RL for complex control tasks. Applications include game playing, robotics, and recommendation systems. Safety and reward hacking are important research areas.' },
  { id: 'ai_07', title: 'Supervised Learning Algorithms', content: 'Supervised learning maps inputs to known outputs using labeled datasets. Classification predicts discrete categories; regression predicts continuous values. Evaluation uses train-validation-test splits and cross-validation. Metrics for classification include accuracy, F1-score, and ROC-AUC. Regularization techniques like L1 and L2 reduce overfitting. Support vector machines find maximum-margin boundaries. Ensemble methods combine weak learners for stronger performance.' },
  { id: 'ai_08', title: 'Unsupervised Learning Techniques', content: 'Unsupervised learning finds patterns without labeled targets. Clustering groups similar points using k-means, hierarchical, or density-based methods. Dimensionality reduction methods like PCA and t-SNE visualize high-dimensional data. Anomaly detection identifies rare events. Association rule mining discovers co-occurrence in transactions. Autoencoders learn compressed representations. Evaluation is harder than supervised settings and often uses intrinsic metrics or downstream task performance.' },
  { id: 'ai_09', title: 'Transformer Architecture', content: 'Transformers replace recurrence with self-attention for sequence modeling. Each token attends to all others to capture long-range dependencies. Multi-head attention learns diverse relationships. Positional encodings inject order information. Encoder-decoder designs power translation; decoder-only models power text generation. Layer normalization and residual connections stabilize training. Transformers scale with data and parameters, enabling foundation models.' },
  { id: 'ai_10', title: 'Large Language Models', content: 'Large language models (LLMs) are transformer-based systems trained on massive text corpora. They exhibit emergent abilities in reasoning, coding, and dialogue. Pretraining objectives include causal language modeling and masked prediction. Instruction tuning and reinforcement learning from human feedback align behavior with user intent. Challenges include hallucinations, bias, privacy, and environmental cost. Retrieval-augmented generation grounds responses in external knowledge.' },
  { id: 'ai_11', title: 'Retrieval-Augmented Generation', content: 'Retrieval-Augmented Generation (RAG) combines information retrieval with language model generation. Documents are chunked, embedded, and stored in vector databases. Queries retrieve relevant passages via similarity search. The LLM generates answers conditioned on retrieved context, improving factual accuracy. Hybrid retrieval merges dense vectors with sparse keyword methods. Reranking improves relevance. Citations increase transparency. Evaluation measures retrieval precision and answer faithfulness.' },
  { id: 'ai_12', title: 'Vector Databases and Embeddings', content: 'Vector databases store high-dimensional embeddings for fast similarity search. Embeddings map text, images, or audio into dense vectors capturing semantic meaning. Approximate nearest neighbor indexes like HNSW enable scalable retrieval. Metadata filters narrow results by domain or date. ChromaDB, Pinecone, and FAISS are popular solutions. Embedding models include sentence transformers and proprietary APIs. Normalization and cosine similarity are standard distance metrics.' },
  { id: 'ai_13', title: 'Model Training and Optimization', content: 'Training neural models minimizes loss functions using gradient descent variants. Learning rate schedules and warmup stabilize convergence. Batch size affects memory and gradient noise. Mixed-precision training accelerates GPUs. Hyperparameter tuning uses grid search, random search, or Bayesian optimization. Early stopping halts training when validation loss plateaus. Distributed training scales across multiple devices for large models.' },
  { id: 'ai_14', title: 'Overfitting and Regularization', content: 'Overfitting occurs when models memorize training noise and fail on new data. Regularization constrains model complexity. Dropout randomly disables neurons during training. Data augmentation artificially expands datasets. L1 sparsity and L2 weight decay penalize large parameters. Simpler models and more data often generalize better. Bias-variance tradeoff guides model selection. Monitoring validation metrics detects overfitting early.' },
  { id: 'ai_15', title: 'Bias and Fairness in AI', content: 'AI systems can perpetuate societal biases present in training data. Fairness metrics evaluate disparate impact across demographic groups. Mitigation includes balanced sampling, adversarial debiasing, and fairness constraints. Transparency through model cards documents limitations. Diverse teams and stakeholder engagement improve outcomes. Regulatory frameworks increasingly require impact assessments. Fairness is context-dependent and requires domain-specific definitions.' },
  { id: 'ai_16', title: 'Explainable AI Methods', content: 'Explainable AI helps users understand model decisions. Intrinsic interpretability uses simple models like linear regression and decision trees. Post-hoc methods include SHAP values, LIME, and attention visualization. Counterfactual explanations show minimal changes altering predictions. Tradeoffs exist between accuracy and interpretability in high-stakes domains like healthcare and lending. Regulations may mandate explanation for automated decisions affecting individuals.' },
  { id: 'ai_17', title: 'AI Ethics and Governance', content: 'AI ethics addresses autonomy, accountability, privacy, and societal impact. Governance frameworks define policies for data use, model deployment, and incident response. Human-in-the-loop systems maintain oversight for critical decisions. Red teaming probes vulnerabilities. International standards and national AI strategies shape industry practice. Ethical AI is not only technical but organizational, requiring leadership commitment and continuous monitoring.' },
  { id: 'ai_18', title: 'Generative AI Applications', content: 'Generative AI creates new content including text, images, audio, and code. Diffusion models synthesize images iteratively denoising latents. GANs pit generator and discriminator networks. Text generation powers chatbots, summarization, and creative writing. Risks include misinformation, copyright issues, and synthetic media abuse. Watermarking and provenance tools help authenticate content. Enterprise adoption focuses on productivity with guardrails.' },
  { id: 'ai_19', title: 'Prompt Engineering Techniques', content: 'Prompt engineering designs inputs that elicit reliable LLM behavior. Zero-shot prompts rely on pretrained knowledge. Few-shot prompts include exemplars demonstrating desired format. Chain-of-thought prompting encourages step-by-step reasoning. System messages define role and constraints. Temperature controls randomness. Structured outputs use JSON schemas. Iterative refinement and evaluation sets improve consistency for production applications.' },
  { id: 'ai_20', title: 'Fine-Tuning and Transfer Learning', content: 'Transfer learning adapts pretrained models to new tasks with less data. Fine-tuning updates some or all model weights on domain-specific corpora. Parameter-efficient methods like LoRA and adapters train small modules. Feature extraction freezes backbone layers. Domain adaptation handles distribution shift between source and target data. Choosing learning rates and epochs prevents catastrophic forgetting of general capabilities.' },
  { id: 'ai_21', title: 'MLOps and Model Deployment', content: 'MLOps applies DevOps practices to machine learning lifecycles. Pipelines version data, code, and models reproducibly. Continuous integration tests training scripts. Continuous deployment serves models via REST or gRPC APIs. Monitoring tracks latency, drift, and error rates. Feature stores centralize transformations. Containerization with Docker and orchestration with Kubernetes scale services. Rollback strategies mitigate bad releases.' },
  { id: 'ai_22', title: 'Edge AI and On-Device Inference', content: 'Edge AI runs models on devices like phones, cameras, and IoT sensors. Benefits include low latency, privacy, and offline operation. Model compression uses quantization, pruning, and knowledge distillation. Hardware accelerators include NPUs and TPUs at the edge. Frameworks like TensorFlow Lite and ONNX Runtime optimize inference. Tradeoffs involve limited memory and power versus cloud-scale models.' },
  { id: 'ai_23', title: 'AI in Healthcare', content: 'AI in healthcare supports diagnosis, treatment planning, and operations. Medical imaging models detect tumors and fractures in radiology. NLP extracts information from clinical notes. Predictive models identify readmission risk. Challenges include regulatory approval, interoperability, and clinician trust. Patient privacy demands HIPAA-compliant data handling. AI augments rather than replaces professional judgment when validated rigorously.' },
  { id: 'ai_24', title: 'AI for Cybersecurity', content: 'Machine learning enhances cybersecurity through anomaly detection, malware classification, and phishing identification. Models analyze network traffic patterns and endpoint logs. Adversarial attacks can evade classifiers, requiring robust training. SOAR platforms automate incident response workflows. False positives must be minimized to avoid alert fatigue. AI also enables offensive capabilities, raising dual-use concerns and defensive countermeasures.' },
  { id: 'ai_25', title: 'Robotics and Embodied AI', content: 'Embodied AI integrates perception, planning, and control in physical robots. Simulators like Gazebo accelerate training before real-world deployment. SLAM builds maps for navigation. Manipulation requires grasp planning and force control. Human-robot collaboration needs safe motion primitives. Sim-to-real transfer bridges simulation gaps. Autonomous vehicles combine computer vision, sensor fusion, and decision systems.' },
  { id: 'ai_26', title: 'Knowledge Graphs and Symbolic AI', content: 'Knowledge graphs represent entities and relationships in structured form. They support query answering, recommendation, and reasoning. Symbolic AI uses logic rules and ontologies. Neuro-symbolic approaches combine neural learning with explicit knowledge. Graph embeddings learn vector representations of nodes. RDF and SPARQL are semantic web standards. Enterprise knowledge management benefits from graph-augmented retrieval.' },
  { id: 'ai_27', title: 'Speech Recognition and Synthesis', content: 'Automatic speech recognition converts audio to text using acoustic and language models. End-to-end architectures simplify traditional pipelines. Text-to-speech generates natural voices via neural vocoders. Speaker identification and diarization segment conversations. Noise robustness and accented speech remain challenges. Voice assistants integrate ASR, NLU, and dialogue management. Accessibility applications benefit visually impaired users.' },
  { id: 'ai_28', title: 'Recommendation Systems', content: 'Recommendation systems personalize content and products. Collaborative filtering uses user-item interaction matrices. Content-based methods use item attributes. Hybrid models combine both signals. Deep learning captures nonlinear patterns. Cold-start problems affect new users and items. Evaluation metrics include precision at k, recall, and NDCG. Ethical issues include filter bubbles and manipulative design.' },
  { id: 'ai_29', title: 'Time Series Forecasting with AI', content: 'Neural networks model temporal dependencies in demand, finance, and IoT data. RNNs, LSTMs, and temporal convolutional networks capture seasonality. Transformers apply attention across time steps. Feature engineering includes lags, rolling statistics, and holidays. Probabilistic forecasts quantify uncertainty. Concept drift requires periodic retraining. Classical ARIMA models remain strong baselines for many series.' },
  { id: 'ai_30', title: 'AutoML and Neural Architecture Search', content: 'AutoML automates model selection, hyperparameter tuning, and pipeline design. Neural architecture search explores network topologies with reinforcement learning or evolutionary algorithms. Tools like Auto-sklearn and H2O democratize machine learning. Benefits include faster experimentation for non-experts. Risks include black-box solutions without domain understanding. Human expertise remains valuable for problem framing and evaluation.' },
  { id: 'ai_31', title: 'Federated Learning', content: 'Federated learning trains models across decentralized devices without sharing raw data. Clients compute local updates; servers aggregate gradients securely. Differential privacy adds noise to protect individuals. Communication efficiency matters for mobile networks. Heterogeneous data distributions challenge convergence. Applications include keyboard predictions and healthcare collaborations across hospitals.' },
  { id: 'ai_32', title: 'Differential Privacy in ML', content: 'Differential privacy provides mathematical guarantees limiting information leakage about individuals. Noise injection during training or query responses enforces privacy budgets. Epsilon and delta parameters quantify privacy loss. Tradeoffs exist between utility and privacy strength. Federated learning often combines with differential privacy. Compliance with GDPR motivates privacy-preserving analytics in enterprise AI.' },
  { id: 'ai_33', title: 'Adversarial Machine Learning', content: 'Adversarial examples are inputs crafted to fool models with imperceptible perturbations. Attacks target classification, detection, and generative systems. Defenses include adversarial training, input preprocessing, and certified robustness. Red teams evaluate model vulnerabilities before deployment. Security-critical applications like autonomous driving require rigorous testing. Understanding attack surfaces guides architecture and monitoring choices.' },
  { id: 'ai_34', title: 'Causal Inference and AI', content: 'Causal inference estimates effects of interventions beyond correlation. Structural causal models represent variables and mechanisms. Randomized experiments provide gold-standard evidence. Observational methods use propensity scores and instrumental variables. ML models often confuse correlation with causation. Causal discovery algorithms infer graphs from data. Policy decisions in economics and medicine benefit from causal reasoning.' },
  { id: 'ai_35', title: 'Graph Neural Networks', content: 'Graph neural networks learn on relational data like social networks and molecules. Message passing aggregates neighbor features iteratively. Applications include fraud detection, drug discovery, and traffic prediction. Heterogeneous graphs contain multiple node and edge types. Scalability uses sampling and distributed training. GNNs complement transformers for structured inductive biases.' },
  { id: 'ai_36', title: 'Multimodal AI Systems', content: 'Multimodal models process text, images, audio, and video jointly. Contrastive learning aligns embeddings across modalities as in CLIP. Vision-language models answer questions about images. Unified transformers tokenize diverse inputs. Applications include document understanding, accessibility, and content moderation. Challenges include alignment quality, hallucination across modalities, and dataset bias.' },
  { id: 'ai_37', title: 'AI Hardware Accelerators', content: 'GPUs parallelize matrix operations essential for deep learning. TPUs optimize tensor computations at scale. NPUs in mobile chips enable efficient inference. Memory bandwidth often bottlenecks training. Cloud providers offer managed GPU clusters. Custom ASICs target specific model architectures. Energy efficiency is increasingly important for sustainable AI scaling.' },
  { id: 'ai_38', title: 'Data Labeling and Annotation', content: 'High-quality labels are critical for supervised learning success. Annotation platforms coordinate human labelers with guidelines. Active learning selects informative samples for labeling. Weak supervision uses noisy heuristics aggregated probabilistically. Inter-annotator agreement measures consistency. Costs scale with task complexity. Synthetic labels from simulations supplement real data in robotics and gaming.' },
  { id: 'ai_39', title: 'Feature Engineering Best Practices', content: 'Feature engineering transforms raw data into informative inputs. Techniques include scaling, encoding categoricals, binning, and polynomial terms. Domain knowledge guides meaningful features in tabular data. Deep learning often learns features automatically from raw signals. Feature stores ensure training-serving consistency. Leakage occurs when future information enters training features, inflating metrics unrealistically.' },
  { id: 'ai_40', title: 'Evaluation Metrics for ML Models', content: 'Choosing metrics aligns with business goals and data characteristics. Imbalanced classification favors precision-recall over accuracy. Regression uses MAE, RMSE, and R-squared. Ranking tasks use MAP and NDCG. Calibration measures probability reliability. Fairness metrics assess subgroup performance. Statistical significance tests compare model variants. Holistic evaluation includes latency, cost, and maintainability.' },
  { id: 'ai_41', title: 'Active Learning Strategies', content: 'Active learning reduces labeling cost by querying the most informative samples. Uncertainty sampling selects points near decision boundaries. Query-by-committee uses disagreement among ensemble models. Diversity sampling covers feature space broadly. Human labelers provide answers for selected batches. Iterative loops retrain models until performance targets are met. Production systems integrate active learning with annotation workflows.' },
  { id: 'ai_42', title: 'Semantic Search Technology', content: 'Semantic search retrieves by meaning rather than exact keyword match. Dense embeddings represent queries and documents in shared vector spaces. Hybrid search combines BM25 lexical scores with vector similarity via reciprocal rank fusion. Query expansion and rewriting improve recall. Rerankers reorder candidates with cross-encoders. Enterprise search benefits from domain-specific fine-tuning and access control metadata.' },
  { id: 'ai_43', title: 'AI Regulation and Compliance', content: 'Governments propose AI acts requiring risk classification and documentation. High-risk applications include hiring, credit scoring, and medical devices. Compliance involves data governance, audit trails, and human oversight. The EU AI Act influences global standards. Organizations maintain model inventories and impact assessments. Legal teams collaborate with engineers on permissible use cases and transparency obligations.' },
  { id: 'ai_44', title: 'Open Source AI Ecosystem', content: 'Open source frameworks include PyTorch, TensorFlow, Hugging Face Transformers, and LangChain. Open weights models enable local deployment and research. Communities share datasets, benchmarks, and reproducibility tools. Licenses vary for commercial use restrictions. Open source accelerates innovation but requires security review of dependencies. Contributions follow governance models like technical steering committees.' },
  { id: 'ai_45', title: 'AI Agents and Tool Use', content: 'AI agents pursue goals by planning actions and using external tools. ReAct patterns interleave reasoning and tool calls. APIs provide calculators, search, databases, and code execution. Memory stores conversation and retrieved facts. Multi-agent systems delegate subtasks. Reliability challenges include error propagation and infinite loops. Guardrails limit permissions and validate outputs before execution.' },
  { id: 'ai_46', title: 'Hallucination Mitigation in LLMs', content: 'Hallucinations are plausible but incorrect LLM outputs. Mitigations include retrieval grounding, confidence calibration, and self-consistency checks. Constrained decoding enforces formats. Human review remains important for high-stakes domains. Evaluation benchmarks measure factual accuracy. Training on curated data and refusal behaviors reduces fabrication. Users should verify critical facts against authoritative sources.' },
  { id: 'ai_47', title: 'Tokenization and Text Preprocessing', content: 'Tokenization splits text into subword units balancing vocabulary size and coverage. Byte-pair encoding and SentencePiece are common algorithms. Preprocessing includes lowercasing, unicode normalization, and stopword removal depending on task. Chunking strategies affect retrieval quality in RAG systems. Metadata extraction captures titles, authors, and sections. Clean corpora improve embedding and generation quality.' },
  { id: 'ai_48', title: 'Cloud AI Services Overview', content: 'Cloud providers offer managed training, inference, and vector search. Services include SageMaker, Vertex AI, Azure OpenAI, and Bedrock. Benefits are scalability and integrated security. Considerations include vendor lock-in, data residency, and cost monitoring. Hybrid architectures keep sensitive data on-premises while using cloud GPUs for burst workloads. API rate limits and SLAs govern production planning.' },
  { id: 'ai_49', title: 'AI Research Frontiers', content: 'Current research explores reasoning, multimodality, efficient training, and alignment. World models simulate environments for planning. Neuroscience inspires architectures. Benchmarks like MMLU and HumanEval measure progress. Open problems include robust generalization, sample efficiency, and value alignment. Interdisciplinary collaboration with social scientists addresses societal impact. Publication peer review and reproducibility remain scientific norms.' },
  { id: 'ai_50', title: 'Building Production RAG Systems', content: 'Production RAG requires ingestion pipelines, vector stores, retrieval tuning, and monitored generation. Document preprocessing includes cleaning, chunking, and metadata extraction. Hybrid retrieval and reranking improve recall and precision. Conversational memory handles follow-up questions. Citations build user trust. Evaluation tracks Precision at K, Recall at K, MRR, hit rate, faithfulness, and latency. Continuous updates refresh knowledge bases as content changes.' },
  { id: 'ai_51', title: 'Convolutional Neural Network Architectures', content: 'CNN architectures stack convolution, pooling, and fully connected layers. Famous designs include LeNet, AlexNet, VGG, ResNet with skip connections, and EfficientNet scaling. Kernels detect local patterns like edges and textures. Stride and padding control spatial dimensions. Batch normalization stabilizes activations. Transfer learning from ImageNet pretrained weights accelerates custom vision tasks.' },
  { id: 'ai_52', title: 'Attention Mechanisms Explained', content: 'Attention computes weighted combinations of values based on query-key compatibility. Scaled dot-product attention divides scores by square root of dimension for stability. Multi-head attention runs parallel attention operations. Self-attention relates positions within one sequence. Cross-attention connects encoder and decoder sequences. Attention maps provide interpretability showing which tokens influence outputs.' },
];

function slugify(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function main() {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  let created = 0;
  AI_DOCUMENTS.forEach((doc) => {
    const filename = `${doc.id}_${slugify(doc.title)}.txt`;
    const filePath = path.join(OUTPUT_DIR, filename);
    const body = `${doc.title}\n${'='.repeat(doc.title.length)}\n\n${doc.content}\n\nDocument ID: ${doc.id}\nCategory: Artificial Intelligence\n`;
    fs.writeFileSync(filePath, body, 'utf-8');
    created++;
  });

  console.log(`Generated ${created} AI domain documents in ${OUTPUT_DIR}`);
}

main();
